/*
 * 070-generate.c — the build-time generator: box sources in, one C file out.
 *
 * What this is: the program that makes "adding a box" mean "writing a
 * function". It reads the C files designated as box sources, finds
 * every function, struct, and compare function in them, and writes one
 * C file containing a shim per box, a table of names to shims and
 * full type information, a field table per struct, and a three-way
 * compare per comparable type.
 *
 * How it does it, in general terms: it does not understand C — it
 * recognizes exactly three top-level shapes in files whose whole
 * purpose is to hold them, and stops loudly on anything else. Every
 * size and offset in its output is a sizeof or offsetof expression, so
 * the compiler computes the numbers and this program never guesses
 * about padding or alignment. Output is written to a temporary file
 * and moved into place only on success, so a failing run can never
 * leave half a file for the build to compile against.
 *
 * Why it is C (issue 308): a program built with this engine should
 * need a C compiler and nothing else. This was a LuaJIT script, which
 * meant every consumer of the engine inherited a build dependency on
 * an interpreter that nothing at run time used. The generator does not
 * depend on the engine it feeds, so it compiles before anything else
 * in the build exists, and there is no bootstrap problem to solve.
 *
 * Usage:
 *   generate <output.c> <box-source.c> [more...]
 *   generate --describe <box-source.c> [more...]
 *     (prints what the parser saw, for diagnosing build problems)
 *
 * Box source ground rules, enforced by the parser, documented once:
 *   - value types are `typedef struct { ... } name;` — plain struct
 *     declarations and inline nested struct bodies are refused; define
 *     nested structs separately and refer to them by name.
 *   - every non-static function is a box; static functions are private
 *     helpers; a function named `type__compare` is that type's
 *     three-way comparison and never becomes a box.
 *   - parameters and returns may be primitives, typedef'd structs, or
 *     `const char *` (a borrowed string — the bytes live wherever the
 *     pointer points, which for a static is the port's own storage).
 */
#include "067-genparse.h"
/* The map reader, so this can say what a description references
 * without the engine having to read text (issue 311d). */
#include "099-mapparse.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* {{{ static void usage() */
static void usage(void)
{
    fprintf(stderr, "usage: generate <output.c> [--root=DIR] "
                    "[--map=FILE]... [--external-boxes] <box.c>...\n");
    fprintf(stderr, "       generate --describe <box.c>...\n");
    fprintf(stderr, "       generate --map-boxes <map>\n");
    fprintf(stderr, "       generate --embed <output.c> <file>...\n");
    exit(65);
}
/* }}} */

/* {{{ static void embed_files() */
/*
 * **Arbitrary files turned into a table of C string literals**, which
 * is stage two of the build that produces `cerac` (issue 910). The
 * engine's header, body and export list go in; a C file defining
 * `cerac_embedded` comes out; `cerac` is compiled from the generator's
 * own sources plus that file and thereafter holds the engine without
 * needing it to exist anywhere on disk.
 *
 * It is a mode of this program rather than a program of its own
 * because the escaping already lives here, and a second tool with a
 * second copy of it would be a second definition of the same rule.
 *
 * The name each file is carried under is its basename. The build hands
 * this absolute paths, and an absolute path from the machine that
 * built `cerac` is exactly the kind of thing this issue exists to stop
 * a shipped binary from carrying.
 *
 * Written whole and then moved into place, for the same reason
 * everything else this program writes is: a run that dies partway must
 * never leave half a file where a build can find it.
 */
static void embed_files(const char *out_path, const char **files, int n_files)
{
    arena_t *a = arena_new();
    buf_t   w;
    buf_init(&w);

    buf_line(&w, "/* GENERATED by scripts/070-generate.c --embed — do not edit,");
    buf_line(&w, " * do not commit. The engine's own source, carried as text so");
    buf_line(&w, " * that the compiler built from this file needs no copy of it");
    buf_line(&w, " * on disk (issue 910). */");
    buf_line(&w, "#include \"143-cerac.h\"");
    buf_line(&w, "");
    buf_line(&w, "#include <string.h>");
    buf_line(&w, "");

    for (int i = 0; i < n_files; i++) {
        size_t n = 0;
        char  *text = gp_read_file(a, files[i], &n);

        buf_line(&w, "static const char cerac_embed_%d[] =", i);
        gt_add_c_string(&w, text, n);
        buf_line(&w, "");
    }

    buf_line(&w, "const cerac_embedded_t cerac_embedded[] = {");
    for (int i = 0; i < n_files; i++) {
        const char *base = strrchr(files[i], '/');
        base = base ? base + 1 : files[i];
        buf_line(&w, "    { \"%s\", cerac_embed_%d },", base, i);
    }
    buf_line(&w, "};");
    buf_line(&w, "const int cerac_n_embedded = %d;", n_files);
    buf_line(&w, "");

    buf_line(&w, "const char *cerac_embedded_text(const char *name)");
    buf_line(&w, "{");
    buf_line(&w, "    for (int i = 0; i < cerac_n_embedded; i++)");
    buf_line(&w, "        if (strcmp(cerac_embedded[i].name, name) == 0)");
    buf_line(&w, "            return cerac_embedded[i].text;");
    buf_line(&w, "    return 0;");
    buf_line(&w, "}");

    char tmp_path[4096];
    snprintf(tmp_path, sizeof tmp_path, "%s.tmp", out_path);
    FILE *f = fopen(tmp_path, "wb");
    if (!f) {
        fprintf(stderr, "generate --embed: cannot write %s\n", tmp_path);
        exit(73);
    }
    fwrite(w.data, 1, w.len, f);
    fclose(f);
    if (rename(tmp_path, out_path) != 0) {
        fprintf(stderr, "generate --embed: cannot move %s into place\n",
                out_path);
        exit(73);
    }

    buf_free(&w);
    arena_free(a);
}
/* }}} */

/* {{{ main */
int main(int argc, char **argv)
{
    if (argc < 2)
        usage();

    int describe_only = strcmp(argv[1], "--describe") == 0;

    /*
     * **Which boxes a description names**, one per line, and nothing
     * else (issue 311d). A program handed a description at run time
     * has to know what it asks for before it can compile it, because
     * a box it does not hold has to be found and compiled first —
     * that is the ordinary path for a description written by a
     * program that had grown, not a rescue.
     *
     * It lives here rather than in the engine because reading text is
     * the compiler's job and the engine does not do it any more. What
     * comes back is exactly what the description said, unresolved:
     * whoever asked knows how to look a name up and this program does
     * not know what they hold.
     */
    /* The files that become `cerac`'s own copy of the engine. Handled
     * before anything else looks at the arguments, because these are
     * not box sources and must not be parsed as any. */
    if (strcmp(argv[1], "--embed") == 0) {
        if (argc < 4)
            usage();
        embed_files(argv[2], (const char **)argv + 3, argc - 3);
        return 0;
    }

    if (strcmp(argv[1], "--map-boxes") == 0) {
        if (argc != 3)
            usage();
        map_description_t *md = mapfile_parse(argv[2]);
        for (desc_station_t *st = md->stations; st; st = st->next)
            printf("%s\n", st->box);
        mapfile_free(md);
        return 0;
    }

    const char *out_path = describe_only ? NULL : argv[1];

    /*
     * The project root, so that a box's path can be shortened before
     * it becomes part of a generated symbol (issue 311a). Without it
     * the symbol carries the absolute path of whatever machine ran
     * the build, which is both enormous and different on every
     * machine — a generated file that differs by where it was built
     * is one nobody can compare against another.
     *
     * Optional: a box compiled while a program runs has no project
     * root to be relative to, and its path is already unique.
     */
    const char *root = NULL;
    const char *sources[argc > 2 ? argc - 2 : 1];
    int n_sources = 0;
    /*
     * **Maps the build was told about** (issue 311d). Each becomes a
     * function that builds it — construction calls, with every box
     * name resolved to a placement function while somebody can still
     * read an error message about it.
     *
     * Named with a flag rather than positionally, because a map file
     * and a box source are both `.c`-adjacent text as far as a shell
     * glob is concerned and telling them apart by extension would be
     * a rule the build has to remember rather than one the caller
     * states.
     */
    const char *maps[argc > 2 ? argc - 2 : 1];
    int n_maps = 0;
    /*
     * **The boxes are already in the process that will load this**
     * (issue 311d). Set when a map is being compiled for a program
     * that is already running: that program was built with these
     * boxes, published the functions that build stations from them,
     * and can bind what is emitted here to what it already holds.
     *
     * So the emitted file declares those functions rather than
     * defining them, and carries nothing else — no call wrappers, no
     * field tables, no second copy of any box. Naming a box that is
     * not actually there fails at load, naming the symbol.
     *
     * Resolution is untouched by this. The sources are still parsed
     * and names are still resolved against them, so a misspelled box
     * is refused here with the same message and the same map line as
     * at build time. Only the emission differs, which is the whole
     * point: one way for a name to be wrong, not two.
     */
    int external_boxes = 0;
    for (int i = 2; i < argc; i++) {
        if (strncmp(argv[i], "--root=", 7) == 0)
            root = argv[i] + 7;
        else if (strncmp(argv[i], "--map=", 6) == 0)
            maps[n_maps++] = argv[i] + 6;
        else if (strcmp(argv[i], "--external-boxes") == 0)
            external_boxes = 1;
        else
            sources[n_sources++] = argv[i];
    }

    /* A map compiled against boxes that are already loaded is the only
     * reason to emit nothing but build functions, so asking for one
     * without the other is a mistake worth naming rather than a
     * quietly empty file. */
    if (external_boxes && n_maps <= 0) {
        fprintf(stderr, "generate: --external-boxes says the boxes are "
                        "already loaded, which only means something when "
                        "there is a map to build from them\n");
        return 64;
    }

    if (n_sources <= 0)
        usage();

    description_t d;
    gp_init(&d);
    for (int i = 0; i < n_sources; i++)
        gp_parse_file(&d, sources[i]);
    gp_validate(&d);

    if (describe_only)
        gp_describe(&d);
    else
        ge_emit(&d, sources, n_sources, maps, n_maps, out_path, root,
                external_boxes);

    gp_free(&d);
    return 0;
}
/* }}} */
